targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
      source_gen:combining_builder:
        options:
          preamble: |
            // coverage:ignore-file