name: knock_flutter
description: A client-side Flutter library to interact with user-facing Knock features, such as feeds.
version: 0.1.1
homepage: https://github.com/knocklabs/knock-flutter

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  phoenix_socket: ^0.6.4

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  pigeon: ^14.0.1
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: app.knock
        pluginClass: KnockPlugin
      ios:
        pluginClass: KnockPlugin