name: Quality Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Flutter configure
        run: flutter config --no-analytics
      - name: Flutter doctor
        run: flutter doctor
      - name: Get dependencies
        run: flutter pub get
      - name: Lint
        run: flutter analyze
      - name: Tests
        run: flutter test --no-pub --machine --coverage --coverage-path lcov.info >> test_report.json
      - name: Publish test results
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: "Test Report"
          path: test_report.json
          reporter: "flutter-json"
          max-annotations: "50"
      - name: Publish coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: success() || failure()
        with:
          lcov-file: lcov.info
          title: "Coverage Report"
